// Code generated by mockery v2.33.3. DO NOT EDIT.

package usecases

import (
	context "context"

	models "github.com/cdumange/notion-htmx-go/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// mockCategoryRepository is an autogenerated mock type for the categoryRepository type
type mockCategoryRepository struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: ctx, category
func (_m *mockCategoryRepository) CreateCategory(ctx context.Context, category models.Category) (uuid.UUID, error) {
	ret := _m.Called(ctx, category)

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Category) (uuid.UUID, error)); ok {
		return rf(ctx, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Category) uuid.UUID); ok {
		r0 = rf(ctx, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Category) error); ok {
		r1 = rf(ctx, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *mockCategoryRepository) GetAll(ctx context.Context) ([]models.Category, error) {
	ret := _m.Called(ctx)

	var r0 []models.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Category, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategory provides a mock function with given fields: ctx, ID
func (_m *mockCategoryRepository) GetCategory(ctx context.Context, ID uuid.UUID) (models.Category, error) {
	ret := _m.Called(ctx, ID)

	var r0 models.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Category, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Category); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Get(0).(models.Category)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockCategoryRepository creates a new instance of mockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCategoryRepository {
	mock := &mockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
