// Code generated by mockery v2.33.3. DO NOT EDIT.

package usecases

import (
	context "context"

	models "github.com/cdumange/notion-htmx-go/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// mockTaskRepository is an autogenerated mock type for the taskRepository type
type mockTaskRepository struct {
	mock.Mock
}

// GetTaskByCategory provides a mock function with given fields: ctx, categoryID
func (_m *mockTaskRepository) GetTaskByCategory(ctx context.Context, categoryID uuid.UUID) ([]models.Task, error) {
	ret := _m.Called(ctx, categoryID)

	var r0 []models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Task, error)); ok {
		return rf(ctx, categoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Task); ok {
		r0 = rf(ctx, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockTaskRepository creates a new instance of mockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTaskRepository {
	mock := &mockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
