// Code generated by mockery v2.43.2. DO NOT EDIT.

package routing

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// mockTaskDeletor is an autogenerated mock type for the taskDeletor type
type mockTaskDeletor struct {
	mock.Mock
}

// DeleteTask provides a mock function with given fields: ctx, ID
func (_m *mockTaskDeletor) DeleteTask(ctx context.Context, ID uuid.UUID) error {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockTaskDeletor creates a new instance of mockTaskDeletor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTaskDeletor(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTaskDeletor {
	mock := &mockTaskDeletor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
