// Code generated by mockery v2.33.3. DO NOT EDIT.

package routing

import (
	context "context"

	models "github.com/cdumange/notion-htmx-go/models"
	mock "github.com/stretchr/testify/mock"
)

// mockGetAllCategoryUC is an autogenerated mock type for the getAllCategoryUC type
type mockGetAllCategoryUC struct {
	mock.Mock
}

// GetCategoriesWithTasks provides a mock function with given fields: ctx
func (_m *mockGetAllCategoryUC) GetCategoriesWithTasks(ctx context.Context) ([]models.Category, error) {
	ret := _m.Called(ctx)

	var r0 []models.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Category, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockGetAllCategoryUC creates a new instance of mockGetAllCategoryUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockGetAllCategoryUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockGetAllCategoryUC {
	mock := &mockGetAllCategoryUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
