name: Code Linting
run-name: Let's ensure it's beautiful
on: [push]
jobs:
  validations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./src
          args: --timeout 3m --verbose
          version: v1.59
      - name: install templ
        run: go install github.com/a-h/templ/cmd/templ@latest
      - name: generate templates
        run: templ generate ./templates/
